// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class Message;
@class MessageBuilder;
@class MessageCheckBlock;
@class MessageCheckBlockBuilder;
@class MessageInfo;
@class MessageInfoBuilder;
@class MessageSemOptions;
@class MessageSemOptionsBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif

typedef NS_ENUM(SInt32, MessageMessageType) {
  MessageMessageTypeHb = 0,
  MessageMessageTypeSemCreate = 1,
  MessageMessageTypeSemDestroy = 2,
  MessageMessageTypeSemP = 3,
  MessageMessageTypeSemV = 4,
  MessageMessageTypeSemCheck = 5,
  MessageMessageTypeCheckBlock = 6,
};

BOOL MessageMessageTypeIsValidValue(MessageMessageType value);

typedef NS_ENUM(SInt32, MessageResponse) {
  MessageResponseOk = 0,
  MessageResponseNo = 1,
  MessageResponseError = 2,
};

BOOL MessageResponseIsValidValue(MessageResponse value);


@interface MessageRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Message : PBGeneratedMessage {
@private
  BOOL hasInfo_:1;
  BOOL hasSemOption_:1;
  BOOL hasCheckBlock_:1;
  BOOL hasType_:1;
  BOOL hasResponse_:1;
  MessageInfo* info;
  MessageSemOptions* semOption;
  MessageCheckBlock* checkBlock;
  MessageMessageType type;
  MessageResponse response;
}
- (BOOL) hasType;
- (BOOL) hasInfo;
- (BOOL) hasResponse;
- (BOOL) hasSemOption;
- (BOOL) hasCheckBlock;
@property (readonly) MessageMessageType type;
@property (readonly, strong) MessageInfo* info;
@property (readonly) MessageResponse response;
@property (readonly, strong) MessageSemOptions* semOption;
@property (readonly, strong) MessageCheckBlock* checkBlock;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageBuilder*) builder;
+ (MessageBuilder*) builder;
+ (MessageBuilder*) builderWithPrototype:(Message*) prototype;
- (MessageBuilder*) toBuilder;

+ (Message*) parseFromData:(NSData*) data;
+ (Message*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message*) parseFromInputStream:(NSInputStream*) input;
+ (Message*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Message*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Message*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MessageInfo : PBGeneratedMessage {
@private
  BOOL hasIpIndex_:1;
  SInt32 ipIndex;
}
- (BOOL) hasIpIndex;
@property (readonly) SInt32 ipIndex;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageInfoBuilder*) builder;
+ (MessageInfoBuilder*) builder;
+ (MessageInfoBuilder*) builderWithPrototype:(MessageInfo*) prototype;
- (MessageInfoBuilder*) toBuilder;

+ (MessageInfo*) parseFromData:(NSData*) data;
+ (MessageInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageInfo*) parseFromInputStream:(NSInputStream*) input;
+ (MessageInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MessageInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MessageInfoBuilder : PBGeneratedMessageBuilder {
@private
  MessageInfo* resultInfo;
}

- (MessageInfo*) defaultInstance;

- (MessageInfoBuilder*) clear;
- (MessageInfoBuilder*) clone;

- (MessageInfo*) build;
- (MessageInfo*) buildPartial;

- (MessageInfoBuilder*) mergeFrom:(MessageInfo*) other;
- (MessageInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIpIndex;
- (SInt32) ipIndex;
- (MessageInfoBuilder*) setIpIndex:(SInt32) value;
- (MessageInfoBuilder*) clearIpIndex;
@end

@interface MessageSemOptions : PBGeneratedMessage {
@private
  BOOL hasValue_:1;
  BOOL hasName_:1;
  SInt32 value;
  NSString* name;
}
- (BOOL) hasName;
- (BOOL) hasValue;
@property (readonly, strong) NSString* name;
@property (readonly) SInt32 value;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageSemOptionsBuilder*) builder;
+ (MessageSemOptionsBuilder*) builder;
+ (MessageSemOptionsBuilder*) builderWithPrototype:(MessageSemOptions*) prototype;
- (MessageSemOptionsBuilder*) toBuilder;

+ (MessageSemOptions*) parseFromData:(NSData*) data;
+ (MessageSemOptions*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageSemOptions*) parseFromInputStream:(NSInputStream*) input;
+ (MessageSemOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageSemOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MessageSemOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MessageSemOptionsBuilder : PBGeneratedMessageBuilder {
@private
  MessageSemOptions* resultSemOptions;
}

- (MessageSemOptions*) defaultInstance;

- (MessageSemOptionsBuilder*) clear;
- (MessageSemOptionsBuilder*) clone;

- (MessageSemOptions*) build;
- (MessageSemOptions*) buildPartial;

- (MessageSemOptionsBuilder*) mergeFrom:(MessageSemOptions*) other;
- (MessageSemOptionsBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageSemOptionsBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (MessageSemOptionsBuilder*) setName:(NSString*) value;
- (MessageSemOptionsBuilder*) clearName;

- (BOOL) hasValue;
- (SInt32) value;
- (MessageSemOptionsBuilder*) setValue:(SInt32) value;
- (MessageSemOptionsBuilder*) clearValue;
@end

@interface MessageCheckBlock : PBGeneratedMessage {
@private
  BOOL hasInitClient_:1;
  BOOL hasSendingClient_:1;
  BOOL hasTargetSem_:1;
  SInt32 initClient;
  SInt32 sendingClient;
  NSString* targetSem;
}
- (BOOL) hasInitClient;
- (BOOL) hasSendingClient;
- (BOOL) hasTargetSem;
@property (readonly) SInt32 initClient;
@property (readonly) SInt32 sendingClient;
@property (readonly, strong) NSString* targetSem;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageCheckBlockBuilder*) builder;
+ (MessageCheckBlockBuilder*) builder;
+ (MessageCheckBlockBuilder*) builderWithPrototype:(MessageCheckBlock*) prototype;
- (MessageCheckBlockBuilder*) toBuilder;

+ (MessageCheckBlock*) parseFromData:(NSData*) data;
+ (MessageCheckBlock*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageCheckBlock*) parseFromInputStream:(NSInputStream*) input;
+ (MessageCheckBlock*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageCheckBlock*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MessageCheckBlock*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MessageCheckBlockBuilder : PBGeneratedMessageBuilder {
@private
  MessageCheckBlock* resultCheckBlock;
}

- (MessageCheckBlock*) defaultInstance;

- (MessageCheckBlockBuilder*) clear;
- (MessageCheckBlockBuilder*) clone;

- (MessageCheckBlock*) build;
- (MessageCheckBlock*) buildPartial;

- (MessageCheckBlockBuilder*) mergeFrom:(MessageCheckBlock*) other;
- (MessageCheckBlockBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageCheckBlockBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasInitClient;
- (SInt32) initClient;
- (MessageCheckBlockBuilder*) setInitClient:(SInt32) value;
- (MessageCheckBlockBuilder*) clearInitClient;

- (BOOL) hasSendingClient;
- (SInt32) sendingClient;
- (MessageCheckBlockBuilder*) setSendingClient:(SInt32) value;
- (MessageCheckBlockBuilder*) clearSendingClient;

- (BOOL) hasTargetSem;
- (NSString*) targetSem;
- (MessageCheckBlockBuilder*) setTargetSem:(NSString*) value;
- (MessageCheckBlockBuilder*) clearTargetSem;
@end

@interface MessageBuilder : PBGeneratedMessageBuilder {
@private
  Message* resultMessage;
}

- (Message*) defaultInstance;

- (MessageBuilder*) clear;
- (MessageBuilder*) clone;

- (Message*) build;
- (Message*) buildPartial;

- (MessageBuilder*) mergeFrom:(Message*) other;
- (MessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (MessageMessageType) type;
- (MessageBuilder*) setType:(MessageMessageType) value;
- (MessageBuilder*) clearType;

- (BOOL) hasInfo;
- (MessageInfo*) info;
- (MessageBuilder*) setInfo:(MessageInfo*) value;
- (MessageBuilder*) setInfoBuilder:(MessageInfoBuilder*) builderForValue;
- (MessageBuilder*) mergeInfo:(MessageInfo*) value;
- (MessageBuilder*) clearInfo;

- (BOOL) hasResponse;
- (MessageResponse) response;
- (MessageBuilder*) setResponse:(MessageResponse) value;
- (MessageBuilder*) clearResponse;

- (BOOL) hasSemOption;
- (MessageSemOptions*) semOption;
- (MessageBuilder*) setSemOption:(MessageSemOptions*) value;
- (MessageBuilder*) setSemOptionBuilder:(MessageSemOptionsBuilder*) builderForValue;
- (MessageBuilder*) mergeSemOption:(MessageSemOptions*) value;
- (MessageBuilder*) clearSemOption;

- (BOOL) hasCheckBlock;
- (MessageCheckBlock*) checkBlock;
- (MessageBuilder*) setCheckBlock:(MessageCheckBlock*) value;
- (MessageBuilder*) setCheckBlockBuilder:(MessageCheckBlockBuilder*) builderForValue;
- (MessageBuilder*) mergeCheckBlock:(MessageCheckBlock*) value;
- (MessageBuilder*) clearCheckBlock;
@end


// @@protoc_insertion_point(global_scope)
